### ISSUE TITLE
All possible config directories should probably be checked, at least the user space ones.

### ISSUE THREAD

**Issue by estysdesu** [davidarmstronglewis/alacritty-theme#1]
You only check the path `$HOME/.config/alacritty/alacritty.yml` as shown.
https://github.com/davidarmstronglewis/alacritty-theme/blob/eacf17dbeb653e99007c4c65aed6530d650725bf/src/lib/alacritty_config.rs#L21

Alacritty mentions that config can be in one of four places. Now, I don't think checking the system space (meaning outside of the user's home directory makes sense), but I think many users use `$HOME/.alacritty.yml` as the config file location. Since this is made public in the docs, I think your code should at least check which config file location is present then change it from there.

P.S. Very new to Rust and just skimmed your code. Not 100% you don't check for the other config file so correct me if I'm wrong. Thanks for the interesting crate!

**Comment by hazel-ocean** [comment]
@estysdesu - you're absolutely right! I've taken a look at what Alacritty is doing and changed this tool to mirror that as closely as possible in a 0.2.0 release.

Thanks for the issue!
